apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: heartbeat
resources:
  - namespace.yaml
  - configmap-config.yaml
  - secret-postgres.yaml
  - postgres.yaml
  - db-collector.yaml
