apiVersion: v1
kind: Secret
metadata:
  name: heartbeat-postgres
  namespace: heartbeat
type: Opaque
stringData:
  username: heartbeat
  password: heartbeat
  database: heartbeat
  dsn: postgres://heartbeat:heartbeat@postgres.heartbeat.svc.cluster.local:5432/heartbeat?sslmode=disable
